name       : pim-data-exporter
version    : 17.12.1
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/pim-data-exporter-17.12.1.tar.xz : 67833e97acd68f9d1ce7e39e1a0900a6e5e770ad16e7f3cc2c12d2b2e800dc67
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : office
optimize   : lto
summary    : Application to archive PIM data
description: |
     Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kio-devel
    - kmail
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailcommon-devel
    - messagelib-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
