name       : pim-data-exporter
version    : 19.08.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/pim-data-exporter-19.08.2.tar.xz : e4703d7a10935814738394a38c5ad54f9923c58e43c397e2e78a4b1b1176f4c2
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailcommon-devel
    - messagelib-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
