name       : pim-data-exporter
version    : 20.12.3
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/pim-data-exporter-20.12.3.tar.xz : 987420ed8accd4a1c9db7baf35807b2c92e1f80eb606aed074b859208829ec9f
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - akonadi-notes-devel
    - kcalendarcore-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kuserfeedback-devel
    - mailcommon-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
