name       : pim-data-exporter
version    : 22.04.1
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/pim-data-exporter-22.04.1.tar.xz : 71bde8eb1fde57087a20c63c38b4d774f93f580b7f3a356196b3fb77f0da6b96
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - akonadi-notes-devel
    - kcalendarcore-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kuserfeedback-devel
    - mailcommon-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
