name       : pim-data-exporter
version    : 18.08.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/pim-data-exporter-18.08.3.tar.xz : 628e62067272b3d8fb6fb7c1fdc9a58e8399a6b708690e1e56e13553536b0f50
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kio-devel
    - kmail
    - kmailtransport-devel
    - kmime-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailcommon-devel
    - messagelib-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
