name       : pim-data-exporter
version    : 21.08.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/pim-data-exporter-21.08.2.tar.xz : aea82b27211049de93260bd3e3689c642b9e88dda658b27dfce4b5c9a7332952
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - akonadi-notes-devel
    - kcalendarcore-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kuserfeedback-devel
    - mailcommon-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
