name       : pim-data-exporter
version    : 22.08.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/pim-data-exporter-22.08.3.tar.xz : 7bd3f629ae76b0ea48f9a27d5cab73a5d8d7f464d175884269bffb2ab52758e3
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Application to archive PIM data
description: |
    Application to assist you with backing up and archiving PIM data, including the necessary configuration, for archival or transfer to another computer.
builddeps  :
    - pkgconfig(Qt5WebEngineWidgets)
    - akonadi-notes-devel
    - kcalendarcore-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kuserfeedback-devel
    - mailcommon-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
